import type { Metadata } from 'next';
import './globals.css';
import AppHeader from '@/components/layout/AppHeader';
import AppFooter from '@/components/layout/AppFooter';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from '@/theme';
import React from 'react';
import { Container } from '@mui/material';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={'tw-bg-[#FAFAFA]'}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <AppHeader />
            <Container
              maxWidth="lg"
              sx={{
                px: {
                  xs: '15px',
                  md: '0 !important',
                },
              }}
            >
              <main>{children}</main>
            </Container>
            <AppFooter />
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
