import type { Metadata } from 'next';
import { useSearchParams, usePathname, useRouter } from 'next/navigation';
import './globals.css';
import AppHeader from '@/components/layout/AppHeader';
import AppFooter from '@/components/layout/AppFooter';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from '@/theme';
import React from 'react';
import { Box } from '@mui/material';
import Script from 'next/script';

export const metadata: Metadata = {
  title: 'PayStandards',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={'tw-bg-[#FAFAFA]'}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <AppHeader />
            <Box
            // sx={
            //   {
            //     mt: {
            //       md: '115px',
            //       xs: '50px',
            //     },
            //   }
            // }
            >
              <main>{children}</main>
            </Box>
            <AppFooter />
          </ThemeProvider>
        </AppRouterCacheProvider>
        <Script src="https://js.hsforms.net/forms/v2.js" strategy={'beforeInteractive'} />
      </body>
    </html>
  );
}
